##########################################################################################################
##
##  Documentation:
##  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html
##
##  Required properties:
##  - GroupDescription
##  - VpcId (for VPC security groups without a default VPC)
##
##########################################################################################################

##########################################################################################################
##
##  Create a new EC2 Security Group. The name for the group is not specified, so 
##  CloudFormation will name it following the structure <STACK_NAME>-EC2SecurityGroup-<STACK_ID>
## (for instance "MyStack-EC2SecurityGroup-1E61QG48YRP8O").
##
##########################################################################################################

AWSTemplateFormatVersion: '2010-09-09'

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: A sample Security Group for EC2 resources